services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: trade-game
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    image: sanyakovlev/trade-game
    ports:
      - "80:8080"
    command: --spring.datasource.url=jdbc:postgresql://db/trade-game
    depends_on:
      db:
        condition: service_healthy